import Foundation
import UIKit

enum ReportFormat: String, CaseIterable, Identifiable {
    case text
    case pdf

    var id: String { rawValue }

    var title: String {
        switch self {
        case .text: "Text Report"
        case .pdf: "PDF Report"
        }
    }
}

struct ReportService {
    static func generateTextReport(for session: TrackingSession) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short

        let timeFormatter = DateFormatter()
        timeFormatter.dateStyle = .none
        timeFormatter.timeStyle = .medium

        var lines: [String] = []
        lines.append("LOCATION TRACKING REPORT")
        lines.append("========================")
        lines.append("")
        lines.append("Trip: \(session.name)")
        lines.append("Started: \(dateFormatter.string(from: session.startDate))")

        if let endDate = session.endDate {
            lines.append("Ended: \(dateFormatter.string(from: endDate))")
        } else {
            lines.append("Ended: In progress")
        }

        lines.append("Duration: \(session.formattedDuration)")
        lines.append("Distance: \(session.formattedDistance)")
        lines.append("Average Speed: \(session.formattedAverageSpeed)")
        lines.append("Waypoints: \(session.points.count)")
        lines.append("")
        lines.append("WAYPOINTS")
        lines.append("---------")

        if session.points.isEmpty {
            lines.append("No location points recorded.")
        } else {
            for (index, point) in session.points.enumerated() {
                lines.append("")
                lines.append("#\(index + 1)")
                lines.append("  Time: \(timeFormatter.string(from: point.timestamp))")
                lines.append("  Coordinates: \(point.formattedCoordinates)")
                lines.append("  Altitude: \(String(format: "%.0f m", point.altitude))")
                lines.append("  Accuracy: ±\(String(format: "%.0f m", point.horizontalAccuracy))")
                lines.append("  Speed: \(point.formattedSpeed)")
            }
        }

        lines.append("")
        lines.append("Generated by Location Tracker on \(dateFormatter.string(from: Date()))")
        return lines.joined(separator: "\n")
    }

    static func generatePDFReport(for session: TrackingSession) -> Data? {
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        let bodyFont = UIFont.systemFont(ofSize: 11)
        let titleFont = UIFont.boldSystemFont(ofSize: 20)
        let headingFont = UIFont.boldSystemFont(ofSize: 13)
        let margin: CGFloat = 48
        let lineHeight: CGFloat = 16
        var y = margin

        let text = generateTextReport(for: session)
        let lines = text.components(separatedBy: "\n")

        return renderer.pdfData { context in
            context.beginPage()

            func drawLine(_ line: String, font: UIFont) {
                if y > pageRect.height - margin {
                    context.beginPage()
                    y = margin
                }

                let attributes: [NSAttributedString.Key: Any] = [.font: font]
                let attributed = NSAttributedString(string: line, attributes: attributes)
                attributed.draw(at: CGPoint(x: margin, y: y))
                y += lineHeight + (font == titleFont ? 8 : 2)
            }

            for line in lines {
                if line == "LOCATION TRACKING REPORT" {
                    drawLine(line, font: titleFont)
                } else if line == "WAYPOINTS" || line == "========================" {
                    y += 6
                    drawLine(line, font: headingFont)
                } else if line.hasPrefix("#") {
                    drawLine(line, font: headingFont)
                } else {
                    drawLine(line, font: bodyFont)
                }
            }
        }
    }

    static func exportURL(for session: TrackingSession, format: ReportFormat) -> URL? {
        let sanitizedName = session.name
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: "/", with: "-")

        let timestamp = ISO8601DateFormatter().string(from: Date())
        let fileName = "\(sanitizedName)_\(timestamp)"

        switch format {
        case .text:
            let text = generateTextReport(for: session)
            let url = FileManager.default.temporaryDirectory
                .appendingPathComponent("\(fileName).txt")
            do {
                try text.write(to: url, atomically: true, encoding: .utf8)
                return url
            } catch {
                return nil
            }

        case .pdf:
            guard let data = generatePDFReport(for: session) else { return nil }
            let url = FileManager.default.temporaryDirectory
                .appendingPathComponent("\(fileName).pdf")
            do {
                try data.write(to: url)
                return url
            } catch {
                return nil
            }
        }
    }
}
